### ISSUE TITLE
windows 版本放弃更新了吗 ？

### ISSUE THREAD

**Issue by douyaolai** [xiaoxin-sky/preemptive_app#1]
windows 版本放弃更新了吗 ？

**Comment by xiaoxin-sky** [comment]
window 可以支持的，没有放弃更新。如果有需要，我将会发布 window 版本，你可以自行 clone 代码编译 window 平台

**Comment by douyaolai** [comment]
> 
我使用你编译好的exe，提示这个：
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"创建VSwitch ap-southeast-1","time":"2022-10-14T05:08:20.376Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"VSwitch已创建，耗时约3443 ms","time":"2022-10-14T05:08:24.480Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"VSwitchId: vsw-t4n6oie6u8m9zfaxlsuel","time":"2022-10-14T05:08:24.480Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"抢占式实例已经创建，实例ID: i-t4ni3oqmenvqvnkit0mf，等待实例启动...","time":"2022-10-14T05:08:27.449Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"实例已启动，耗时约15460 ms","time":"2022-10-14T05:08:42.910Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"实例SSH连接信息: IP：8.219.178.234, 端口: 22, 账户: root, 密码: AliSpot@1949203e8d009","time":"2022-10-14T05:08:42.911Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"SSH连接中...","time":"2022-10-14T05:08:42.911Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":40,"msg":"SSH连接失败，重试第1次...","time":"2022-10-14T05:08:50.591Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"SSH已连接；开始启用GoogleBBR...","time":"2022-10-14T05:08:52.511Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"GoogleBBR已启用，耗时约105168 ms；系统重启...","time":"2022-10-14T05:10:37.681Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"实例已重启，耗时约10371 ms","time":"2022-10-14T05:10:48.052Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":30,"msg":"SSH已重新连接；开始安装SSR Server...","time":"2022-10-14T05:10:55.664Z","v":0}
{"name":"alispot","hostname":"DELLPROS","pid":13248,"level":60,"err":{"message":"Cannot read property 'port' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'port' of undefined\n    at main (D:\\Program Files\\alispot-master\\index.js:276:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"Cannot read property 'port' of undefined","time":"2022-10-14T05:11:04.509Z","v":0}

**Comment by xiaoxin-sky** [comment]
看上去这个日志是 [alispot](https://github.com/rockswang/alispot) 的，不是preemptive_app的，如果你使用的是 [alispot](https://github.com/rockswang/alispot)，那你需要去 [alispot](https://github.com/rockswang/alispot) 提出 issue。

**Comment by douyaolai** [comment]
> 看上去这个日志是 [alispot](https://github.com/rockswang/alispot) 的，不是preemptive_app的，如果你使用的是 [alispot](https://github.com/rockswang/alispot)，那你需要去 [alispot](https://github.com/rockswang/alispot) 提出 issue。

不好意思，确实是 alispot的，正在看你的 preemptive_app ，
我这边是Windows 10 ，下载了你的工程文件后，请问 在哪配置 阿里密钥这些信息，然后如何编译 ，先 npm i ,然后 npm run build  吗 ？

**Comment by xiaoxin-sky** [comment]
如果你需要我手动构建的话，可以查看一下 tuari.app build 相关文档。或者等待我发布window

**Comment by douyaolai** [comment]
> tuari.app build

好的，我先看看，继续关注 项目 ！

**Comment by douyaolai** [comment]
> 如果你需要我手动构建的话，可以查看一下 tuari.app build 相关文档。或者等待我发布window
> […](#)
> 在 2022年10月15日，12:24，yuyanke ***@***.***> 写道： ﻿ 看上去这个日志是 alispot 的，不是preemptive_app的，如果你使用的是 alispot，那你需要去 alispot 提出 issue。 不好意思，确实是 alispot的，正在看你的 preemptive_app ， 我这边是Windows 10 ，下载了你的工程文件后，请问 在哪配置 阿里密钥这些信息，然后如何编译 ，先 npm i ,然后 npm run build 吗 ？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
刚搜了 tuari.app build  ，我还是等待你的Windows exe 文件 吧！

**Comment by douyaolai** [comment]
@xiaoxin-sky 大佬，啥时候更新 Windows 版本啊

**Comment by xiaoxin-sky** [comment]
> @xiaoxin-sky 大佬，啥时候更新 Windows 版本啊

https://github.com/xiaoxin-sky/preemptive_app/releases/tag/v0.0.1
已经支持 window.
